export const demoUsers = [
  {
    id: "user-ahmed-raza",
    handle: "@ahmed.karachi",
    name: "Ahmed Raza",
    age: "38",
    gender: "male",
    city: "Karachi",
    country: "Pakistan",
    phone: "300 1234567",
    maritalStatus: "Divorced",
    profession: "Business Owner",
    education: "Bachelor's in Commerce",
    livingSituation: "Own house",
    children: "2 children from previous marriage",
    incomeRange: "Rs. 2,00,000+",
    sect: "Sunni",
    prayer: "Regular prayer",
    quran: "Can recite Quran",
    familyType: "Nuclear family preferred",
    photoPrivacy: "Blur before mutual match",
    photo:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    cover:
      "https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&w=900&q=80",
    bio:
      "I value honesty, faith, family involvement, and a peaceful home. I am looking for a sincere partner who understands the responsibilities of a second marriage.",
    tags: ["Traditional", "Educated", "Responsible", "Family-first"],
    verification: ["ID", "Family", "Professional"],
    preferences: {
      ageMin: "28",
      ageMax: "45",
      location: "Same city",
      maritalStatus: "Either",
      openToChildren: true,
      prayerImportance: "Important",
    },
    stats: {
      views: 245,
      likes: 12,
      matches: 3,
      completion: 75,
      superLikes: 0,
      boosts: 1,
    },
  },
  {
    id: "user-fatima-khan",
    handle: "@fatima.teacher",
    name: "Fatima Khan",
    age: "32",
    gender: "female",
    city: "Karachi",
    country: "Pakistan",
    phone: "301 2233445",
    maritalStatus: "Widow",
    profession: "School Teacher",
    education: "Master's in Education",
    livingSituation: "With family",
    children: "2 children, ages 5 and 8",
    sect: "Sunni",
    prayer: "Regular prayer",
    quran: "Can recite with Tajweed",
    familyType: "Joint family",
    photoPrivacy: "Show to verified profiles only",
    photo:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
    bio:
      "I am a teacher and mother of two. I value faith, patience, and family-centered decisions. I am looking for a kind and responsible partner who respects children and elders.",
    tags: ["Widow", "Teacher", "2 children", "Family verified"],
    verification: ["ID", "Family"],
    compatibility: 85,
  },
  {
    id: "user-sana-ali",
    handle: "@sana.lahore",
    name: "Sana Ali",
    age: "31",
    gender: "female",
    city: "Lahore",
    country: "Pakistan",
    phone: "302 5566778",
    maritalStatus: "Divorced",
    profession: "Doctor",
    education: "MBBS",
    livingSituation: "With family",
    children: "No children",
    sect: "Sunni",
    prayer: "5 times daily",
    quran: "Can recite Quran",
    familyType: "Nuclear family preferred",
    photoPrivacy: "Show after mutual match",
    photo:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
    bio:
      "My family is involved in this process from the beginning. I appreciate direct, respectful communication and a peaceful home environment.",
    tags: ["Divorced", "Doctor", "Verified", "Family-first"],
    verification: ["ID", "Professional"],
    compatibility: 91,
  },
  {
    id: "user-maryam-siddiqui",
    handle: "@maryam.isb",
    name: "Maryam Siddiqui",
    age: "40",
    gender: "female",
    city: "Islamabad",
    country: "Pakistan",
    phone: "303 4455667",
    maritalStatus: "Widow",
    profession: "Business Owner",
    education: "Bachelor's in Commerce",
    livingSituation: "Own house",
    children: "1 child",
    sect: "Shia",
    prayer: "Regular prayer",
    quran: "Learning",
    familyType: "Nuclear family",
    photoPrivacy: "Blur before mutual match",
    photo:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
    bio:
      "I am looking for sincerity, emotional maturity, and a family that understands the responsibilities of second marriage.",
    tags: ["Widow", "Business", "Family-first", "Verified"],
    verification: ["Family"],
    compatibility: 78,
  },
  {
    id: "user-ayesha-noor",
    handle: "@ayesha.noor",
    name: "Ayesha Noor",
    age: "35",
    gender: "female",
    city: "Karachi",
    country: "Pakistan",
    phone: "304 9988776",
    maritalStatus: "Divorced",
    profession: "Lecturer",
    education: "MPhil",
    livingSituation: "With parents",
    children: "1 child, age 7",
    sect: "Sunni",
    prayer: "Regular prayer",
    quran: "Can recite Quran",
    familyType: "Joint family",
    photoPrivacy: "Show after mutual match",
    photo:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
    bio:
      "I believe a second marriage should begin with clarity, patience, and family blessings. I value education and kindness.",
    tags: ["Lecturer", "Karachi", "Family verified", "Educated"],
    verification: ["ID", "Family"],
    compatibility: 88,
  },
  {
    id: "user-hamza-qureshi",
    handle: "@hamza.lahore",
    name: "Hamza Qureshi",
    age: "42",
    gender: "male",
    city: "Lahore",
    country: "Pakistan",
    phone: "305 1122334",
    maritalStatus: "Widower",
    profession: "Engineer",
    education: "Master's",
    livingSituation: "Own house",
    children: "3 children",
    incomeRange: "Rs. 2,00,000+",
    sect: "Sunni",
    prayer: "5 times daily",
    quran: "Can recite Quran",
    familyType: "Nuclear family",
    photo:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
    bio:
      "A responsible father looking for a mature partner who values faith, children, and a peaceful family life.",
    tags: ["Widower", "Engineer", "Father", "Verified"],
    verification: ["ID", "Professional"],
    compatibility: 82,
  },
  {
    id: "user-bilal-hassan",
    handle: "@bilal.isb",
    name: "Bilal Hassan",
    age: "36",
    gender: "male",
    city: "Islamabad",
    country: "Pakistan",
    phone: "306 2233445",
    maritalStatus: "Divorced",
    profession: "Civil Servant",
    education: "Master's",
    livingSituation: "Own house",
    children: "No children",
    incomeRange: "Rs. 1,00,000-2,00,000",
    sect: "Sunni",
    prayer: "Regular prayer",
    quran: "Can recite Quran",
    familyType: "Joint family",
    photo:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80",
    bio:
      "I am serious about marriage and prefer early family involvement. I value honesty and a balanced religious lifestyle.",
    tags: ["Divorced", "Civil Servant", "Islamabad", "Verified"],
    verification: ["ID"],
    compatibility: 80,
  },
  {
    id: "user-zainab-saleem",
    handle: "@zainab.saleem",
    name: "Zainab Saleem",
    age: "29",
    gender: "female",
    city: "Multan",
    country: "Pakistan",
    phone: "307 3344556",
    maritalStatus: "Divorced",
    profession: "Designer",
    education: "Bachelor's",
    livingSituation: "With family",
    children: "No children",
    sect: "Sunni",
    prayer: "Occasional",
    quran: "Learning",
    familyType: "Nuclear family",
    photo:
      "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?auto=format&fit=crop&w=900&q=80",
    bio:
      "I am rebuilding life with optimism and family support. I am looking for someone respectful, educated, and patient.",
    tags: ["Designer", "Divorced", "Creative", "Family-first"],
    verification: ["Family"],
    compatibility: 73,
  },
  {
    id: "user-usman-farooq",
    handle: "@usman.farooq",
    name: "Usman Farooq",
    age: "45",
    gender: "male",
    city: "Karachi",
    country: "Pakistan",
    phone: "308 4455667",
    maritalStatus: "Currently married",
    profession: "Trader",
    education: "Intermediate",
    livingSituation: "Separate residence planned",
    children: "4 children",
    incomeRange: "Rs. 2,00,000+",
    sect: "Sunni",
    prayer: "Regular prayer",
    quran: "Can recite Quran",
    firstWifeConsent: true,
    plannedArrangement: "Separate residence and fair financial responsibility.",
    photo:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=80",
    bio:
      "Seeking a second marriage within Islamic guidelines, with consent, financial clarity, and family awareness.",
    tags: ["Second marriage", "Consent declared", "Karachi", "Business"],
    verification: ["ID", "Professional"],
    compatibility: 69,
  },
  {
    id: "user-nadia-rahman",
    handle: "@nadia.rahman",
    name: "Nadia Rahman",
    age: "37",
    gender: "female",
    city: "Peshawar",
    country: "Pakistan",
    phone: "309 5566778",
    maritalStatus: "Widow",
    profession: "Homemaker",
    education: "Intermediate",
    livingSituation: "With family",
    children: "3 children",
    sect: "Sunni",
    prayer: "5 times daily",
    quran: "Can recite Quran",
    familyType: "Joint family",
    photo:
      "https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?auto=format&fit=crop&w=900&q=80",
    bio:
      "I am family-oriented and religiously practicing. I want a kind partner who is open to children and elder involvement.",
    tags: ["Widow", "Homemaker", "Religious", "Children"],
    verification: ["ID", "Family"],
    compatibility: 76,
  },
];

export const currentUserId = "user-ahmed-raza";

export const initialMessages = [
  {
    id: "msg-1",
    conversationId: "match-ayesha",
    senderId: "user-ayesha-noor",
    receiverId: currentUserId,
    from: "them",
    text: "السلام علیکم. Thank you for connecting.",
    time: "10:12 AM",
    createdAt: "2026-05-25T05:12:00.000Z",
  },
  {
    id: "msg-2",
    conversationId: "match-ayesha",
    senderId: currentUserId,
    receiverId: "user-ayesha-noor",
    from: "me",
    text: "Wa Alaikum Assalam. I appreciate your message. Family involvement is important to me.",
    time: "10:14 AM · Read",
    createdAt: "2026-05-25T05:14:00.000Z",
  },
  {
    id: "msg-3",
    conversationId: "match-ayesha",
    senderId: "user-ayesha-noor",
    receiverId: currentUserId,
    from: "them",
    text: "That is good to know. My elder brother helps review profiles before we move forward.",
    time: "10:16 AM",
    createdAt: "2026-05-25T05:16:00.000Z",
  },
];

export const initialMatches = [
  {
    id: "match-ayesha",
    userId: currentUserId,
    matchedUserId: "user-ayesha-noor",
    matchedAt: "2026-05-25T05:10:00.000Z",
    unread: 2,
  },
  {
    id: "match-sana",
    userId: currentUserId,
    matchedUserId: "user-sana-ali",
    matchedAt: "2026-05-24T19:30:00.000Z",
    unread: 0,
  },
  {
    id: "match-maryam",
    userId: currentUserId,
    matchedUserId: "user-maryam-siddiqui",
    matchedAt: "2026-05-23T16:20:00.000Z",
    unread: 0,
  },
];

export const initialFamilyMembers = [
  {
    id: "family-hassan",
    userId: currentUserId,
    name: "Hassan Raza",
    relation: "Brother",
    phone: "+92 300 7654321",
    permission: "View + suggest matches",
  },
];

export const initialNotifications = [
  {
    id: "note-match",
    type: "match",
    title: "It's a match with Ayesha",
    time: "2m",
    read: false,
  },
  {
    id: "note-views",
    type: "activity",
    title: "Your profile was viewed 7 times today",
    time: "1h",
    read: false,
  },
  {
    id: "note-review",
    type: "system",
    title: "Your ID verification is under review",
    time: "3h",
    read: true,
  },
];

export const initialSubscription = {
  tier: "Basic",
  status: "free",
  superLikes: 0,
  boosts: 1,
  incognito: false,
};

export const initialFilters = {
  ageMin: "28",
  ageMax: "45",
  location: "Same city",
  verifiedOnly: false,
  openToChildren: true,
  recentlyActive: false,
  prayerImportant: true,
  familyInvolvement: true,
};

export const premiumTiers = [
  {
    id: "basic",
    name: "Basic",
    label: "Current",
    price: "Free",
    features: ["10 likes per day", "Basic matching", "Standard support"],
  },
  {
    id: "gold",
    name: "Gold",
    label: "Recommended",
    price: "Rs. 2,499 / mo",
    features: [
      "Unlimited likes",
      "5 Super Likes daily",
      "See who likes you",
      "Rewind passes",
      "Advanced filters",
    ],
  },
  {
    id: "platinum",
    name: "Platinum",
    label: "Ultimate",
    price: "Rs. 4,999 / mo",
    features: [
      "Everything in Gold",
      "Dedicated relationship advisor",
      "Priority profile placement",
      "Expedited verification",
    ],
  },
];

export function createInitialAppState() {
  return {
    currentUserId,
    profiles: demoUsers,
    currentUser: demoUsers.find((profile) => profile.id === currentUserId),
    matches: initialMatches,
    messages: initialMessages,
    familyMembers: initialFamilyMembers,
    notifications: initialNotifications,
    subscription: initialSubscription,
    filters: initialFilters,
    reports: [],
    interactions: [],
  };
}
